config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  resources :work_orders
  resources :time_cards

  root 'home#index'

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :work_orders
  has_many :time_cards
end

app/models/time_card.rb
class TimeCard < ActiveRecord::Base
  belongs_to :employee
end

app/models/work_order.rb
class Work_Order < ActiveRecord::Base
  belongs_to :employee

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController
  before_action :set_time_card, only: [:show, :edit, :update, :destroy]

  # GET /time_cards
  # GET /time_cards.json
  def index
    @time_cards = TimeCard.all
  end

  # GET /time_cards/1
  # GET /time_cards/1.json
  def show
  end

  # GET /time_cards/new
  def new
    @time_card = TimeCard.new
  end

  # GET /time_cards/1/edit
  def edit
  end

  # POST /time_cards
  # POST /time_cards.json
  def create
    @time_card = TimeCard.new(time_card_params)

    respond_to do |format|
      if @time_card.save
        format.html { redirect_to @time_card, notice: 'Time card was successfully created.' }
        format.json { render :show, status: :created, location: @time_card }
      else
        format.html { render :new }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_cards/1
  # PATCH/PUT /time_cards/1.json
  def update
    respond_to do |format|
      if @time_card.update(time_card_params)
        format.html { redirect_to @time_card, notice: 'Time card was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_card }
      else
        format.html { render :edit }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_cards/1
  # DELETE /time_cards/1.json
  def destroy
    @time_card.destroy
    respond_to do |format|
      format.html { redirect_to time_cards_url, notice: 'Time card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_card
      @time_card = TimeCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_card_params
      params.require(:time_card).permit(:date, :employee_id, :morning_in, :morning_out, :afternoon_in, :afternoon_out)
    end
end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  before_action :set_work_order, only: [:show, :edit, :update, :destroy]

  # GET /work_orders
  # GET /work_orders.json
  def index
    @work_orders = Work_Order.all
  end

  # GET /work_orders/1
  # GET /work_orders/1.json
  def show
  end

  # GET /work_orders/new
  def new
    @work_order = Work_Order.new
  end

  # GET /work_orders/1/edit
  def edit
  end

  # POST /work_orders
  # POST /work_orders.json
  def create
    @work_order = Work_Order.new(work_order_params)

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to @work_order, notice: 'Work order was successfully created.' }
        format.json { render :show, status: :created, location: @work_order }
      else
        format.html { render :new }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /work_orders/1
  # PATCH/PUT /work_orders/1.json
  def update
    respond_to do |format|
      if @work_order.update(work_order_params)
        format.html { redirect_to @work_order, notice: 'Work order was successfully updated.' }
        format.json { render :show, status: :ok, location: @work_order }
      else
        format.html { render :edit }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1
  # DELETE /work_orders/1.json
  def destroy
    @work_order.destroy
    respond_to do |format|
      format.html { redirect_to work_orders_url, notice: 'Work order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work_order
      @work_order = Work_Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_order_params
      params.require(:work_order).permit(:wo_nbr, :description, :employee, :customer, :hours, :start_date, :end_date, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/time_cards_helper.rb
module TimeCardsHelper
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/home/index.html.erb
<h1>Baxter Engines CMS</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Baxter Engines CMS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <%= link_to "Home", root_path %>
    <%= link_to "Work Orders", work_orders_path %>
    <%= link_to "Time Cards", time_cards_path %>
  </nav>

<%= yield %>

</body>
</html>

app/views/time_cards/_form.html.erb
<%= form_for(@time_card) do |f| %>
  <% if @time_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_card.errors.count, "error") %> prohibited this time card from being saved:</h2>

      <ul>
      <% @work_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.number_field :employee_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>
  <div class="field">
    <%= f.label :morning_in %><br>
    <%= f.time_select :morning_in %>
  </div>
  <div class="field">
    <%= f.label :morning_out %><br>
    <%= f.time_select :morning_out %>
  </div>
  <div class="field">
    <%= f.label :afternoon_in %><br>
    <%= f.time_select :afternoon_in %>
  </div>
  <div class="field">
    <%= f.label :afternoon_out %><br>
    <%= f.time_select :afternoon_out %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_cards/edit.html.erb
<h1>Editing Time Card</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_card %> |
<%= link_to 'Back', time_cards_path %>

app/views/time_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Time Cards</h1>

<table>
  <thead>
    <tr>
      <th>Employee</th>
      <th>Date</th>
      <th>Morning In</th>
      <th>Morning Out</th>
      <th>Afternoon In</th>
      <th>Afternoon Out</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_cards.each do |time_card| %>
      <tr>
        <td><%= time_card.employee_id %></td>
        <td><%= time_card.date %></td>
        <td><%= time_card.morning_in %></td>
        <td><%= time_card.morning_out %></td>
        <td><%= time_card.afternoon_in %></td>
        <td><%= time_card.afternoon_out %></td>
        <td><%= link_to 'Show', time_card %></td>
        <td><%= link_to 'Edit', edit_time_card_path(time_card) %></td>
        <td><%= link_to 'Destroy', time_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time card', new_time_card_path %>

app/views/time_cards/new.html.erb
<h1>New Time Card</h1>

<%= render 'form' %>

<%= link_to 'Back', time_cards_path %>

app/views/time_cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_time_card_path(@time_card) %> |
<%= link_to 'Back', time_cards_path %>

app/views/work_orders/_form.html.erb
<%= form_for(@work_order) do |f| %>
  <% if @work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
      <% @work_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wo_nbr %><br>
    <%= f.number_field :wo_nbr %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :employee %><br>
    <%= f.text_field :employee %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :hours %><br>
    <%= f.text_field :hours %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/work_orders/edit.html.erb
<h1>Editing Work Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @work_order %> |
<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Work Orders</h1>

<table>
  <thead>
    <tr>
      <th>Wo nbr</th>
      <th>Description</th>
      <th>Employee</th>
      <th>Customer</th>
      <th>Hours</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @work_orders.each do |work_order| %>
      <tr>
        <td><%= work_order.wo_nbr %></td>
        <td><%= work_order.description %></td>
        <td><%= work_order.employee %></td>
        <td><%= work_order.customer %></td>
        <td><%= work_order.hours %></td>
        <td><%= work_order.start_date %></td>
        <td><%= work_order.end_date %></td>
        <td><%= work_order.notes %></td>
        <td><%= link_to 'Show', work_order %></td>
        <td><%= link_to 'Edit', edit_work_order_path(work_order) %></td>
        <td><%= link_to 'Destroy', work_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work Order', new_work_order_path %>

app/views/work_orders/new.html.erb
<h1>New Work Order</h1>

<%= render 'form' %>

<%= link_to 'Back', work_orders_path %>

app/views/work_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wo nbr:</strong>
  <%= @work_order.wo_nbr %>
</p>

<p>
  <strong>Description:</strong>
  <%= @work_order.description %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @work_order.employee %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @work_order.customer %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @work_order.hours %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @work_order.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @work_order.end_date %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @work_order.notes %>
</p>

<%= link_to 'Edit', edit_work_order_path(@work_order) %> |
<%= link_to 'Back', work_orders_path %>